# START autogenerated for Eloqua
[[ -s "/Users/matkins/.rvm/scripts/rvm" ]] && source "/Users/matkins/.rvm/scripts/rvm"  # This loads RVM into a shell session.
# END autogenerated for Eloqua

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
source $(brew --prefix nvm)/nvm.sh
source /Users/matkins/.rvm/scripts/rvm
